name: Shodan and Nuclei Workflow with Go

on:
  workflow_dispatch:  # Manual trigger for the workflow

jobs:
  shodan_nuclei_scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Repository
    - name: Checkout Repository
      uses: actions/checkout@v3

     # Step 2: Pull the Nuclei Docker Image
    - name: Pull Nuclei Docker Image
      run: docker pull projectdiscovery/nuclei:latest

    # Step 3: Run Nuclei Scan
    - name: Run Nuclei with Docker
      run: |
        # Create a targets.txt file with your target(s)
        echo "https://polywood.com" > targets.txt
        mkdir results  # Ensure results directory exists
        docker run --rm \
          -v $(pwd):/nuclei \
          projectdiscovery/nuclei:latest \
          -l /nuclei/targets.txt \
          -t CVE-2024-50603.yaml \
          -o /nuclei/results/results.txt

    # Step 8: Upload Results as Artifact
    - name: Upload Scan Results
      uses: actions/upload-artifact@v3
      with:
        name: scan-results
        path: results.txt
